### ISSUE TITLE
☂️ linter: eslint-plugin-react (recommended)

### ISSUE THREAD

**Issue by camc314** [web-infra-dev/oxc#1022]
https://github.com/jsx-eslint/eslint-plugin-react (recommended)

## Recommended rules

- [ ] [display-name](docs/rules/display-name.md)
- [x] [jsx-key](docs/rules/jsx-key.md) #1016 
- [ ] [jsx-no-comment-textnodes](docs/rules/jsx-no-comment-textnodes.md)
- [ ] [jsx-no-duplicate-props](docs/rules/jsx-no-duplicate-props.md)
- [ ] [jsx-no-target-blank](docs/rules/jsx-no-target-blank.md)
- [ ] [jsx-no-undef](docs/rules/jsx-no-undef.md)
- [ ] [jsx-uses-react](docs/rules/jsx-uses-react.md)
- [ ] [jsx-uses-vars](docs/rules/jsx-uses-vars.md)
- [ ] [no-children-prop](docs/rules/no-children-prop.md) #1015 
- [ ] [no-danger-with-children](docs/rules/no-danger-with-children.md)
- [ ] [no-deprecated](docs/rules/no-deprecated.md)
- [ ] [no-direct-mutation-state](docs/rules/no-direct-mutation-state.md)
- [ ] [no-find-dom-node](docs/rules/no-find-dom-node.md)
- [ ] [no-is-mounted](docs/rules/no-is-mounted.md)
- [ ] [no-render-return-value](docs/rules/no-render-return-value.md)
- [ ] [no-string-refs](docs/rules/no-string-refs.md)
- [ ] [no-unescaped-entities](docs/rules/no-unescaped-entities.md)
- [ ] [no-unknown-property](docs/rules/no-unknown-property.md)
- [ ] [prop-types](docs/rules/prop-types.md)
- [ ] [react-in-jsx-scope](docs/rules/react-in-jsx-scope.md)
- [ ] [require-render-return](docs/rules/require-render-return.md)            
- [ ] [jsx-no-useless-fragment](docs/rules/jsx-no-useless-fragment.md) #1021

**Comment by XantreGodlike** [comment]
Pls, update checkboxes :)

**Comment by IWANABETHATGUY** [comment]
> Pls, update checkboxes :)

Done

**Comment by XantreGodlike** [comment]
jsx-no-undef done too

**Comment by XantreGodlike** [comment]
Are the way of getting react version from some plugin?
I think it's necessary for [no-deprecated](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md)

https://github.com/jsx-eslint/eslint-plugin-react/blob/ca162fdc5dc37f9f3447640a5a14a91daf73ea47/lib/util/version.js#L74C1-L100C2
```ts
const defaultVersion = '999.999.999';

function getReactVersionFromContext(context) {
  let confVer = defaultVersion;
  // .eslintrc shared settings (https://eslint.org/docs/user-guide/configuring#adding-shared-settings)
  if (context.settings && context.settings.react && context.settings.react.version) {
    let settingsVersion = context.settings.react.version;
    if (settingsVersion === 'detect') {
      settingsVersion = detectReactVersion(context);
    }
    if (typeof settingsVersion !== 'string') {
      error('Warning: React version specified in eslint-plugin-react-settings must be a string; '
        + `got “${typeof settingsVersion}”`);
    }
    confVer = String(settingsVersion);
  } else if (!warnedForMissingVersion) {
    error('Warning: React version not specified in eslint-plugin-react settings. '
      + 'See https://github.com/jsx-eslint/eslint-plugin-react#configuration .');
    warnedForMissingVersion = true;
  }
  confVer = /^[0-9]+\.[0-9]+$/.test(confVer) ? `${confVer}.0` : confVer;
  const result = semver.coerce(confVer.split('.').map((part) => Number(part)).join('.'));
  if (!result) {
    error(`Warning: React version specified in eslint-plugin-react-settings must be a valid semver version, or "detect"; got “${confVer}”`);
  }
  return result ? result.version : defaultVersion;
}
```

**Comment by keita-hino** [comment]
I'm going to begin tackling the `react/void-dom-elements-no-children`.

**Comment by keita-hino** [comment]
I will start working on the task of `react/checked-requires-onchange-or-readonly`.

**Comment by keita-hino** [comment]
I will start working on the `react/jsx-props-no-spread-multi` task.

**Comment by ChangeHow** [comment]
Did [exhaustive-deps)](https://oxc.rs/docs/guide/usage/linter/rules/react/exhaustive-deps.html) already support autofix?

**Comment by PeterCardenas** [comment]
seems like [`react/jsx-uses-vars`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md) should be covered by the existing `eslint/no-unused-vars` rule?

**Comment by jadejr** [comment]
The rationale for react/prefer-read-only-props is incorrect. It applies to functional components as well (at least in oxlint).

I wonder if that's the case for any other of the other rules.

**Comment by mbrevda** [comment]
With the inclusion of the React compiler, is there any update to the React compiler-specific ruler?

**Comment by connorshea** [comment]
> With the inclusion of the React compiler, is there any update to the React compiler-specific ruler?

You can use them all via `react/react-compiler` but it is explicitly experimental and may have bugs. The plan will be to split up the compiler rule into separate rules in the same way it was split up in the original react-hooks implementation, but we want to stabilize the react-compiler implementation first, so for now it's an all-or-nothing thing.

https://oxc.rs/docs/guide/usage/linter/rules/react/react-compiler.html

**Comment by Vladexy88x** [comment]
I will start working on the task of `react/no-invalid-html-attribute`

**Comment by connorshea** [comment]
> With the inclusion of the React compiler, is there any update to the React compiler-specific ruler?

This has been merged and the react-compiler rule will now be available as various separate rules with the release on Monday.
