### ISSUE TITLE
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y (recommended)

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/oxc#1141]

**Comment by Boshen** [comment]
cc @manzt

**Comment by manzt** [comment]
## Tasks:

- [ ] [accessible-emoji](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/accessible-emoji.md)
- [x] [alt-text](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/alt-text.md) https://github.com/oxc-project/oxc/pull/1126
- [ ] [anchor-ambiguous-text](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/anchor-ambiguous-text.md)
- [ ] [anchor-has-content](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/anchor-has-content.md)
- [ ] [anchor-is-valid](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/anchor-is-valid.md)
- [ ] [aria-activedescendant-has-tabindex](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-activedescendant-has-tabindex.md)
- [ ] [aria-props](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-props.md)
- [ ] [aria-proptypes](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-proptypes.md)
- [ ] [aria-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-role.md)
- [ ] [aria-unsupported-elements](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-unsupported-elements.md)
- [ ] [autocomplete-valid](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/autocomplete-valid.md)
- [ ] [click-events-have-key-events](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/click-events-have-key-events.md)
- [ ] [control-has-associated-label](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/control-has-associated-label.md)
- [ ] [heading-has-content](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/heading-has-content.md)
- [ ] [html-has-lang](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/html-has-lang.md)
- [ ] [iframe-has-title](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/iframe-has-title.md)
- [ ] [img-redundant-alt](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/img-redundant-alt.md)
- [ ] [interactive-supports-focus](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/interactive-supports-focus.md)
- [ ] [label-has-associated-control](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md)
- [ ] [label-has-for](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-for.md)
- [ ] [lang](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/lang.md)
- [ ] [media-has-caption](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/media-has-caption.md)
- [ ] [mouse-events-have-key-events](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/mouse-events-have-key-events.md)
- [ ] [no-access-key](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-access-key.md)
- [ ] [no-aria-hidden-on-focusable](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-aria-hidden-on-focusable.md)
- [ ] [no-autofocus](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-autofocus.md)
- [ ] [no-distracting-elements](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-distracting-elements.md)
- [ ] [no-interactive-element-to-noninteractive-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-interactive-element-to-noninteractive-role.md)
- [ ] [no-noninteractive-element-interactions](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-noninteractive-element-interactions.md)
- [ ] [no-noninteractive-element-to-interactive-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-noninteractive-element-to-interactive-role.md)
- [ ] [no-noninteractive-tabindex](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-noninteractive-tabindex.md)
- [ ] [no-onchange](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-onchange.md)
- [ ] [no-redundant-roles](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-redundant-roles.md)
- [ ] [no-static-element-interactions](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-static-element-interactions.md)
- [ ] [prefer-tag-over-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/prefer-tag-over-role.md)
- [ ] [role-has-required-aria-props](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/role-has-required-aria-props.md)
- [ ] [role-supports-aria-props](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/role-supports-aria-props.md)
- [ ] [scope](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/scope.md)
- [ ] [tabindex-no-positive](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/tabindex-no-positive.md)

**Comment by msdlisper** [comment]
@Boshen  @manzt  Can you assign me the task of `anchor-has-content`?

**Comment by manzt** [comment]
Feel free to make a PR and reference this issue!

**Comment by JustFly1984** [comment]
This plugin is a great, though nobody maintains eslint plugin for a long time.

**Comment by XantreGodlike** [comment]
Obsolete tasks
Done: lang, media-has-caption

**Comment by XantreGodlike** [comment]
Can I try to implement some aria rules using [biome_aria](https://docs.rs/biome_aria/0.3.1/biome_aria/index.html) crate?

**Comment by Boshen** [comment]
> @Boshen Can I try to implement some aria rules using [biome_aria](https://docs.rs/biome_aria/0.3.1/biome_aria/index.html) crate? For example: role-has-required-aria-props

We are porting https://www.npmjs.com/package/aria-query over to https://github.com/oxc-project/aria-query with @Shinyaigeek, is biome_aria the samething, but the APIs look different.

**Comment by XantreGodlike** [comment]
> > @Boshen Can I try to implement some aria rules using [biome_aria](https://docs.rs/biome_aria/0.3.1/biome_aria/index.html) crate? For example: role-has-required-aria-props
> 
> We are porting https://www.npmjs.com/package/aria-query over to https://github.com/oxc-project/aria-query with @Shinyaigeek, is biome_aria the samething, but the APIs look different.

What do you want to benefit from it? Are `biome_aria` slow?

**Comment by Boshen** [comment]
> > > @Boshen Can I try to implement some aria rules using [biome_aria](https://docs.rs/biome_aria/0.3.1/biome_aria/index.html) crate? For example: role-has-required-aria-props
> > 
> > 
> > We are porting https://www.npmjs.com/package/aria-query over to https://github.com/oxc-project/aria-query with @Shinyaigeek, is biome_aria the samething, but the APIs look different.
> 
> What do you want to benefit from it? Are `biome_aria` slow?

I didn't know it's existence until you mentioned it, I'll take a deeper look when I get some time next week.

**Comment by Shinyaigeek** [comment]
> What do you want to benefit from it? Are biome_aria slow?

`biome_aria` looks totally different from `aria-query`. `aria-query` has the also about DOM elements, but `biome_aria` does not. I interpret that `biome_aria` is made to aggregate the aria related data for biome (maybe specieally for biome’s linter), and is not alternative of `aria-query`, so it’s API is different. 

Considering that oxc will provide an interface for linter plugins defined in userland in the future, I believe that it is advantageous from the viewpoint of easy transition and ecosystem development to provide not only aria data but also dom elements and other data for such users, and to provide an API equivalent to aria-query (but just in my opinion).

**Comment by XantreGodlike** [comment]
Maybe, I've just seen that biome uses biome_aria for aria jsx rules. https://github.com/biomejs/biome/blob/b99e7856e99d656675d688d75a875570382f9c71/crates/biome_js_analyze/src/aria_analyzers/a11y/use_aria_props_for_role.rs#L49

**Comment by keita-hino** [comment]
I will start working on the task of `aria-activedescendant-has-tabindex`.

**Comment by regexyl** [comment]
I've started implementation for `label-has-associated-control`, but it looks like they're still a couple of kinks to work out for the original implementation:

- https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/972
- https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/966
- https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/962
- https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/961

I'll try jumping over there and see if there's anything I can help out with before looping back here :)

**Comment by mehm8128** [comment]
I will work on implementing [jsx-a11y/aria-proptypes](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/aria-proptypes.md).

**Comment by mehm8128** [comment]
I'd like to work on `jsx-a11y/interactive-supports-focus` if there are no blocking issues.

**Comment by anarefolio** [comment]
I'd like to work on jsx-a11y/no-interactive-element-to-noninteractive-role if there are no blocking issues

**Comment by camchenry** [comment]
Closing this as complete now. We've implemented all rules listed in the original issue. I think we should continue to iterate in other issues as we find opportunities to improve and fix issues. Thank you all for your help in getting this done!
