### ISSUE TITLE
Re-enable the minifier 

### ISSUE THREAD

**Issue by DonIsaac** [web-infra-dev/oxc#947]
We needed to disable `oxc_minifier` when we removed the HIR (`oxc_hir` and `oxc_ast_lower`) since it relies heavily on it. Re-enabling the minifier requires us to update its implementation to rely on the "normal" AST implementation (`oxc_ast`).

This requires 3 high-level steps:
1. Support scope entry/exit in some visitor, replacing `oxc_hir`'s `Visit` trait
2. Replace usage of `oxc_hir` and `oxc_ast_lower` structs/traits (e.g. `HirKind`, `HirBuilder`, `Hir::Expression`, etc) with corresponding `oxc_ast` structs/traits
3. Update compressor/mangler/printer logic to handle "new" AST nodes

## Task List
- [ ] feat(ast): support entering/exiting scopes in `Visit` and `VisitMut`
- [ ] refactor(ast): move utility functions from `hir_utils.rs` into `oxc_ast`
- [ ] fix(minifier): migrate printer to `oxc_ast`
- [ ] fix(minifier): migrate compressor to `oxc_ast`
- [ ] fix(minifier): migrate mangler to `oxc_ast`

**Comment by Boshen** [comment]
The remaining issue for the mangler is that the visitor lacks symbol information:

https://github.com/web-infra-dev/oxc/blob/14e1dacd0a21ff34fb8a2efaba525b8a452a73d7/crates/oxc_minifier/src/mangler/mod.rs#L85-L86
